data_dir: 'data/'
cur_dataset_dir: 'data/jsons/json_format/'

vocab_dir: 'data/vocab/'
token_vocab_file: 'token_vocab.txt'
char_vocab_file: 'char_vocab.txt'
prd_type_vocab_file: 'prd_type_vocab.txt'
role_type_vocab_file: 'role_type_vocab.txt'
action_vocab_file: 'action_vocab.txt'
pos_vocab_file: 'pos_vocab.txt'
dep_type_vocab_file: 'dep_type_vocab.txt'
udog_type_vocab_file: 'udog_type_vocab.txt'

eval_dir: 'data/eval/'
write_eval_file_dev: 'eval_file_dev.txt'
write_eval_file_test: 'eval_file_test.txt'
save_eval_file_test: 'results.txt'

pickle_dir: 'data/pickle/'
vec_npy: 'word_vec.npy'
inst_pl_file: 'data.pl'
model_save_file: 'model.ckpt'




embedding_dir: ''
embedding_file: 'glove.840B.300d.txt'
embedding_type: 'glove.840B.300d'


normalize_digits: false
lower_case: false