
# train config
msg_info: 'Opinion Role Labeling'
random_seed: 2435
num_epochs: 100
batch_size: 8
init_lr: 0.0015
decay_lr: 0.8
minimum_lr: 0.0002
patience: 5
grad_clipping: 10.0
unk_ratio: 0.2
weight_decay: 5e-5


# embedding config
use_sentence_vec: false

sent_vec_project: 0
sent_vec_project_activation: 'linear'
# concat sentence vector after BiLSTM
# if cat_sent_after_rnn is false, we concat sent_vec and word_embed, before BiLSTM
cat_sent_after_rnn: false
encoder_project:  0 #200
# use random initialized word embedding
random_word_embed: false

# use pre-trained word embedding, not contextualized one.
use_pretrain_embed: true
# tuning pre-trained embedding
pretrain_embed_tune: true

word_embed_trainable: true
word_embed_dim: 300
word_project_dim: 200

use_char_rnn: true
char_embed_dim: 40
char_rnn_dim: 40

dp_emb: 0.43

use_pos: false
pos_embed_dim: 50


use_dep: false
dep_embed_dim: 50
treeLSTM_dim: 100


# LSTM and stack LSTM config
use_rnn_encoder: true
encoder_layer: 2
rnn_dim: 150
dp_rnn: 0.23


lmda_rnn_dim: 300
#part_ent_rnn_dim: 100
action_rnn_dim: 60
out_rnn_dim: 60
dp_state: 0.15
dp_state_h: 0.1
dp_buffer: 0.
dp_stack: 0.15

# output config
output_hidden_dim: 250
dp_out: 0.5

# for tree rnn config
action_embed_dim: 50
ds_embed_dim: 50
role_embed_dim: 50
ds_position_dim: 50
#arg_embed_dim: 50

use_arg_type_tree: true

max_sent_len: 100
max_word_len: 20
max_target_length: 10


# for RCGA
n_rcga_layer: 2
rcga_in_features: 300
rcga_out_features: 300
rcga_dropout: 0.2
rcga_concat: true
udog_embed_dim: 50
udog_role_dim: 50
length_embed_dim: 50